import type { Metadata } from 'next'
import { Theme, Container } from '@radix-ui/themes'
import Navbar from '@/components/navbar'

import '@radix-ui/themes/styles.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme appearance='dark' accentColor='cyan'>
          <Container>
            <Navbar />
            {children}
          </Container>
        </Theme>
      </body>
    </html>
  )
}
